# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enc_message',
        ),
    ]
