# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_enc_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enc_message',
            field=models.TextField(default=django.utils.timezone.now, max_length=40000),
            preserve_default=False,
        ),
    ]
